// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnpvmbsbsxvoqmrawzwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucHZtYnNic3h2b3FtcmF3end0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDQ0MzYsImV4cCI6MjA3MTcyMDQzNn0.wTKFGR04hE03dqFILNiMDCE2KdoGMp4i_oLbcu7-dYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});